name: Gradle
on:
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      OTEL_SERVICE_NAME: gradle
      OTEL_RESOURCE_ATTRIBUTES: service.name=gradle
    steps:
      - name: Ckeckout
        uses: actions/checkout@v4
        with:
          repository: v1v/gradle-otel-tracing
          ref: feature/add-otel-plugin

      - name: gradle build
        run: ./gradlew clean build

      - name: gradle test
        run: ./gradlew clean test
