name: pyTest
on:
  workflow_dispatch:
  schedule:
    - cron: "* */5 * * 1-5"
    
permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Ckeckout
        uses: actions/checkout@v4
        with:
          repository: kuisathaverat/pytest_otel
          ref: main
      - name: demo
        run: |
          python -m venv .venv
          . .venv/bin/activate
          pip install ".[test]" 
          python -m pytest --capture=no docs/demos/test/test_demo.py
